# <font color= 'teal'>_Numpy_ :</font>
   <font size = 3.5> Numpy stands for Numerical Python and it is the core library for numeric and scientific computing. </font>
  


### Single Dimensional Array


In [1]:
import numpy as np

In [3]:
n1 = np.array([10,20,30,40])
n1


array([10, 20, 30, 40])

In [4]:
type(n1)

numpy.ndarray

### Multi Dimensional Array

In [6]:
n2 = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])
n2

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [7]:
type(n2)

numpy.ndarray

### Initializing Numpy array with Zeros

In [12]:
n3 = np.zeros((2,4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Initialize Numpy array with same number

In [14]:
n5 = np.full((5,5),10)
n5

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [16]:
n6 = np.full((2,6),111)
n6

array([[111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111]])

### Initialize Numpy array within a particular range

In [17]:
n7 = np.arange(10,51)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [21]:
n8 = np.arange(0,101,5)
n8

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

### Initialize Numpy array with random numbers

In [24]:
n9 = np.random.randint(10,50,5)
n9

array([44, 31, 24, 10, 47])

### Checking the Shape of an Array

In [25]:
n10 = np.array([[1,2,3,4],[5,6,7,8]])
n10

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
n10.shape

(2, 4)

In [28]:
n10.shape = (4,2)

In [29]:
n10

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

***

## Joining Numpy Arrays
   ##### vstack()
   ##### hstack()
   ##### column_stack()

In [30]:
n11 = np.array([1,2,3,4])
n12 = np.array([5,6,7,8])

In [31]:
np.vstack((n11,n12))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.hstack((n11,n12))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.column_stack((n11,n12))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Numpy Intersection & Difference

In [34]:
n13 = np.array([10,20,30,40,50,60])
n14 = np.array([50,60,70,80,90])

In [35]:
np.intersect1d(n13,n14)

array([50, 60])

In [36]:
np.setdiff1d(n13,n14)

array([10, 20, 30, 40])

In [37]:
np.setdiff1d(n14,n13)

array([70, 80, 90])

### Numpy Array Mathematics

In [38]:
n15 = np.array([10,20])
n16 = np.array([30,40])

In [39]:
np.sum([n15,n16])

100

In [40]:
np.sum([n15,n16], axis = 0)

array([40, 60])

In [41]:
np.sum([n15,n16], axis = 1)

array([30, 70])

### Numpy Array Basic Mathematics

##### Basic Addition

In [42]:
n17 = np.array([10,20,30,40])

In [44]:
n17 + 100 

array([110, 120, 130, 140])

##### Basic Subtraction

In [45]:
n17 - 5

array([ 5, 15, 25, 35])

##### Basic Multiplication

In [46]:
n17 * 5

array([ 50, 100, 150, 200])

##### Basic Division

In [47]:
n17/10

array([1., 2., 3., 4.])

***

### Numpy Mean

In [48]:
n18 = np.array([10,25,33,48,50])

In [49]:
np.mean(n18)

33.2

### Numpy Standard Deviation

In [50]:
np.std(n18)

14.878171930717832

### Numpy Median

In [56]:
np.median(n18)

33.0

***

## Saving & Loading Numpy Array

In [52]:
n19 = np.array([10,20,30,40,50,60])

In [53]:
np.save('final_array',n19)

In [54]:
n20 = np.load('final_array.npy')

In [55]:
n20

array([10, 20, 30, 40, 50, 60])